name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test image
        run: |
          docker buildx build \
            --target testing \
            --cache-from=type=registry,ref=ghcr.io/${{ github.repository }}/cloudylist-test:cache \
            --cache-to=type=inline \
            -t ghcr.io/${{ github.repository }}/cloudylist-test:latest \
            --push .

      - name: Run tests with coverage
        env:
          COVERAGE: 80
        run: |
          docker run --rm \
            -e COVERAGE=${{ env.COVERAGE }} \
            ghcr.io/${{ github.repository }}/cloudylist-test:latest

      - name: Generate coverage report
        run: |
          docker run --rm \
            -e COVERAGE=term-missing \
            ghcr.io/${{ github.repository }}/cloudylist-test:latest \
            --cov-report=html
          tar -czf coverage-html.tar.gz htmlcov

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-html.tar.gz
