name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    name: Build and Test Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test image
        run: |
          docker buildx build --target testing \
            --cache-from=type=registry,ref=ghcr.io/${{ github.repository }}/cloudylist-cache:latest \
            --cache-to=type=registry,ref=ghcr.io/${{ github.repository }}/cloudylist-cache:latest,mode=max \
            -t ghcr.io/${{ github.repository }}/cloudylist-test:latest .

      - name: Run unit tests
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/cloudylist-test:latest

      - name: Build production image
        run: |
          docker buildx build --target production \
            --cache-from=type=registry,ref=ghcr.io/${{ github.repository }}/cloudylist-cache:latest \
            --cache-to=type=registry,ref=ghcr.io/${{ github.repository }}/cloudylist-cache:latest,mode=max \
            -t ghcr.io/${{ github.repository }}/cloudylist:latest .

      - name: Push production image
        run: |
          docker push ghcr.io/${{ github.repository }}/cloudylist:latest
